### ISSUE TITLE
after login does not redirect

### ISSUE THREAD

**Issue by knives177** [tylerbrawl/Galaxy-Plugin-Rockstar#154]
Hi, 
as the title suggests, after logging in, he cannot complete the operation by returning to the final page

![image](https://user-images.githubusercontent.com/80071544/159774553-4b222b7b-6bb6-4828-b6a3-8d0cf5332e3e.png)

**Comment by tylerbrawl** [comment]
This issue was fixed some time ago in a separate update, but it seems like Galaxy 2.0 isn't retrieving it.

In the meantime, you can download and install the latest version yourself. I posted instructions for it [here](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/issues/150#issuecomment-1074466754). With that said, I'll close this issue for now. If the issues persist after the new version is installed, then please reply to this issue, and I can re-open it.
