### ISSUE TITLE
Rockstar Plugin Not Detecting Game Activity

### ISSUE THREAD

**Issue by christofin** [tylerbrawl/Galaxy-Plugin-Rockstar#16]
Hey Tyler,

I've been testing your plugin and I noticed that it's not detecting game activity even when I launch the games through GOG 2.0. 

I have two games through the Rockstar Launcher: Bully Scholarship Edition, and Grand Theft Auto: San Andreas. 

Your plugin was able to detect both games and launches them without issue. 

The problem is that it doesn't detect the play activity. To make sure that this wasn't an issue with the current version of GOG 2.0, I added Tetris Effect as a .exe and ran it, and GOG 2.0 was able to detect my playtime and count the exact total of minutes I've played. 

I then added Bully as a game through the add game menu in the upper left of GOG 2.0, and linked GOG 2.0 manually to the Bully: Scholarship Edition .exe. When I ran the game through Bully (manually added .exe), instead of Bully: Scholarship Edition (the same .exe but found through your plugin), it counted my playtime. This indicates that it isn't an issue with the .exe (of either Bully or GTA:SA), but something with the Rockstar Launcher integration. 

For what it's worth, I also downloaded the community integration for Blizzard, and it isn't counting my Overwatch time either, when launching through GOG 2.0. 

Let me know how I can help test this. I can set a temp password for my Rockstar account and let you log in and test the behavior if you need to. 

Thanks!

**Comment by christofin** [comment]
![bullys](https://user-images.githubusercontent.com/43354771/67908530-32390b00-fb52-11e9-8707-2152722301d5.PNG)
![bully](https://user-images.githubusercontent.com/43354771/67908531-32390b00-fb52-11e9-968d-611fd97a3a48.PNG)

**Comment by tylerbrawl** [comment]
The reason for this is that the Galaxy API requires that integrations provide a means for the client to import the user's game time, rather than being able to track it for itself. This allows for a more accurate tracking of play time than just recording the time spent playing after the game is launched from Galaxy 2.0 (since it also displays the time played outside of Galaxy), but it means that the client is unable to track the play time itself.

The time for Bully is being tracked because it is unaffiliated with any integration (i.e., the .exe file was manually added). Since it is not possible (at least to my knowledge) to directly scrape the play time from the Social Club website, the only current "solution" would be to keep a cached copy of a user's total played time. This poses two issues:
- The play time would only be tracked when the game is launched from the Galaxy client.
- The play time would likely be lost if the user ever logs out or loses authentication. This can be remedied by saving the play time locally on disk, but that also poses the issue of allowing users to "fake" their play time.

If anybody can devise a better solution, then I would be happy to hear it. As it is now, however, this might be the only one. (I do know that the Rockstar Games Launcher keeps track of and displays the user's played time within the settings menu of individual games, and it is likely that it keeps a cached copy somewhere on disc, but I am not sure how to access it.)

**Comment by christofin** [comment]
I think you're correct that Rockstar tracks time on a game to game basis, and to make things more difficult, sometimes it's not even for the entire game. For GTA V, your playtime is totaled separately for each of the three single player characters, and separately for online, so four places in total. For RDR2, I believe it's just a separate playtime for single player and online. 

I sent an email to the feedback line at Rockstar (mouthoff@rockstargames.com) asking for globally tracked playtime, but I doubt that would be implemented anytime soon, if at all... I think for now the best workaround would be saving the playtime on the disk and allowing players to fake it if they really wanted to.

**Comment by tylerbrawl** [comment]
That seems like the best option for now. I highly doubt Rockstar would want to listen to anybody regarding this, so we would be on our own for that. Still, I really would appreciate it if the play time was recorded consistently on the Social Club.

**Comment by tylerbrawl** [comment]
The latest pre-release allows tracking the user's play time for each game, but I have yet to store the time data locally in a separate file. (However, the play time is saved until the user loses authentication with the Rockstar plugin.) If you wish, you can test it as a sort of proof of concept.

**Comment by christofin** [comment]
![rockstarstuck](https://user-images.githubusercontent.com/43354771/68090179-ac151100-fe3e-11e9-96fa-8579ac2fc24d.PNG)

Thanks, Tyler. I'm not able to test it because for some reason over the last few days, my Rockstar plugin is stuck on connecting even though my credentials haven't changed. I tried deleting the plugin, restarting, and installing 0.2.1, then the same for 0.2.2, and now the 0.3 preview, but it still is stuck on connecting. 

My Rockstar tab is still in the sidebar and it lets me launch the games, but as soon as I close out the Play button is greyed out, as if GOG 2.0 doesn't detect an install. Very strange.

**Comment by christofin** [comment]
![pluginsfolder](https://user-images.githubusercontent.com/43354771/68090205-03b37c80-fe3f-11e9-82e3-dbeeb3d01628.PNG)

This is what my plugins folder looks like ^

**Comment by tylerbrawl** [comment]
Would you be able to upload your log file for this plugin? The eternal "Connecting" message suggests that the issue is certainly with the plugin, and not with your computer.

**Comment by christofin** [comment]
Sure, I wasn't able to find a specific log file so I uploaded the entire folder for the plugin to Google Drive. Hopefully this is helpful. If the log file is stored in a different location on my computer I can find it and upload it. Here's a link to the Google Drive folder for the Rockstar plugin:

https://drive.google.com/drive/folders/1_iSjfGK_qMIvz6MgVz_hwIf8KqGEC6BZ?usp=sharing

As for other plugins, I did notice that my Blizzard plugin crashed from the Awesome GOG plugins. Awesome GOG was how I first downloaded your plugin, up until I started manually extracting the releases into the "installed" folder to test your new features. 

I can confirm that it's still stuck on connecting this morning. I can launch my games I own via the Rockstar launcher when I first open GOG 2.0, but as soon as I close out, the play button is greyed out, so I think the issues are related. 

I'll be able to test the playtime tracking once this is resolved. Let me know if there's anything else I can do to help.

**Comment by tylerbrawl** [comment]
This is not where the log file for the plugin is, despite what it might seem. The log file is actually found in this location:

```C:\ProgramData\GOG.com\Galaxy\logs\plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log```

If you are unable to find the ProgramData folder on the root of your C: drive, make sure that you have enabled the setting to view hidden files and folders on Windows Explorer. ([This Microsoft article](https://support.microsoft.com/en-us/help/4028316/windows-view-hidden-files-and-folders-in-windows-10) describes how to enable this setting on Windows 10.) Lastly, make sure that you have the latest pre-release of v0.3 installed for relevance, and that you attempt to connect with the plugin at least once with this version before submitting the log.

**Comment by christofin** [comment]
[plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/3806194/plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log)

Here you go, thanks. I'm on the latest version. I did force close GOG and tested this on 0.2.2 and did the same process for 0.2.1 and it was still an issue there, so I don't think it's version specific. It seems to have happened after I tested 0.3 but reverting back to a previous release still has the issue present. If there's a better way to revert to a previous plugin I'd be happy to try.

**Comment by tylerbrawl** [comment]
You know what? I believe this error is being caused because it is trying to use your log-in from v0.2.X, while the log-in system for v0.3 uses a different system. (I can offer a more in-depth explanation, if you wish.)

I know that you said that you tried uninstalling and reinstalling the plugin, but the log file does indeed suggest that my hypothesis is correct. Are you given the option to disconnect your account? If so, disconnect and then reconnect. If not, then you would have to find a way to delete the cache that Galaxy 2.0 creates for the plugin to reset the log-in. I am not sure of where this is located.

**Comment by christofin** [comment]
Makes perfect sense. I don't have any option to disconnect, but if we could cause the plugin to crash or fail then I should have that option in the settings panel of GOG 2.0. Alternatively if we can try figuring out how to clear the plugin cache, I can try that. I'll check the GOG 2.0 forums.

**Comment by tylerbrawl** [comment]
Here is a modified plugin that should log you out if it detects a previous log-in. It also incorporates additional changes, such as saving the user's play time to the disk so that it does not get erased if they lose authentication. If this works for you, then I will release this as v0.3 (Pre-Release 2).

Also, thank you for responding to all of my comments so promptly. You have been a great help!
[plugin.zip](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/3806417/plugin.zip)

**Comment by christofin** [comment]
I can confirm that it caused me to log out and I was able to log back in, nice work! I'll test the playtime tracking now. 

And it's no problem. I don't plan on buying RDR2 on Rockstar so I won't have any games to test the achievement support when you implement it, but I'll be happy to test anything else you plan to add. This is a great plugin and I'm really excited to be able to help test it. If you ever wanted to even use something like Chrome Remote Support to see what things look like from my end, I'd be happy to do that.

**Comment by christofin** [comment]
Playtime tracking is working, thanks a bunch. We can resolve this ticket and if you want to reach out to me for any other testing, feel free to shoot me a message on Reddit or email me at c.mcdonald13@gmail.com.

**Comment by tylerbrawl** [comment]
I appreciate your support. I will go ahead and release this new version as a pre-release.
