### ISSUE TITLE
Plugins Frequently Disconnecting

### ISSUE THREAD

**Issue by olegbl** [tylerbrawl/Galaxy-Plugin-Rockstar#59]
Half the time I start up GOG, the Rockstar plugin is disconnected and I have to re-connect it by entering username/password again.

Attached: [Plugin logs (inside a zip 'cause GitHub doesn't like txt)](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/3929956/plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.copy.log.zip)

Looks like a bunch of 400 Bad Requests during auth.

Edit: forgot to mention:
* Windows 10
* plugin v0.3.6
* GOG v2.0.9
* Rockstar launcher v308897 / 1.0.16.196.1 / 2.0.4.3 (why do they have a build number and *two* version numbers?)

**Comment by tylerbrawl** [comment]
It seems like the plugin is failing to refresh credentials during authentication. This *might* be caused by a failure to update required cookies, but I am not certain from looking at the provided log file alone. 

Could you try downloading and installing the [v0.4-Pre3](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/releases/tag/v0.4-Pre3) plugin version? It drastically changes authentication flow (again), but I have not had a single disconnect since. This version makes sure to update all cookies in the session object that were set in a response. In addition, it appears to actually be very stable; I am just waiting to be able to test various social features before I send it to the ```fog_release``` branch for publishing. (@FriendsOfGalaxy, does the user presence feature work in Galaxy 2.0 right now, or has it only been added to the API for later use?)

(Side Note: I know that the first version number for the Rockstar Games Launcher (```1.0.16.196.1```) is the version of the launcher client itself, and the purpose of the build number should be fairly obvious. The second version number (```2.0.4.3```) likely refers to their API version, as some of the Social Club source code references a v2 of an API which I presume belongs to games only (i.e., GTA V, RDR 2, and L.A. Noire).)

**Comment by olegbl** [comment]
> Could you try downloading and installing the v0.4-Pre3 plugin version?

Will do! Thanks!

> The second version number (2.0.4.3) likely refers to their API version

Interesting!

**Comment by olegbl** [comment]
0.4pre3 has been working solid last few days! Thanks!

**Comment by tylerbrawl** [comment]
I'm glad to hear it! I have been waiting for user presence to work correctly before releasing `v0.4` as a final release (see #60 for details).
